name: Pipeline de CI/CD FIAP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código
      uses: actions/checkout@v2

    - name: Configurar ambiente .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7' 

    - name: Restaurar pacotes
      run: dotnet restore

    - name: Publicar aplicação
      run: dotnet publish -c Release -o ./publish

    - name: Configurar ambiente Kubernetes
      uses: azure/aks-set-context@v1
      with:
        cluster-name: FIAP 
        resource-group: FIAPKUBERNETESAKS  
        kubeconfig: ${{ secrets.KUBECONFIG_SECRET_NAME }} 

    - name: Fazer login no registro Docker (se necessário)
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construir imagem Docker
      run: docker build -t sua-imagem-docker:latest .

    - name: Publicar imagem Docker
      run: docker push sua-imagem-docker:latest

    - name: Implantação no Kubernetes
      run: kubectl apply -f deployment.yaml 

    - name: Esperar implantação concluir
      run: kubectl wait --for=condition=available deployment/sua-imagem-deployment