name: CI/CD AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      run: az acr login --name <your-acr-name>

    - name: Build and push Docker image
      run: |
        docker build -t <your-acr-name>/my-app:${{ github.sha }} .
        docker push <your-acr-name>/my-app:${{ github.sha }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f kubernetes-manifests/deployment.yaml
        kubectl rollout restart deployment my-app
